### ISSUE TITLE
PubSub + Monitor Support

### ISSUE THREAD

**Issue by wilgaboury** [AscendingCreations/RedisPool#4]
This library has it's own pool connection type that is a wrapper around an underlying `ConnectionLike`, that is only exposed as a reference. The `into_pubsub` and into `into_monitor` function for [`Connection`](https://docs.rs/redis/latest/redis/aio/struct.Connection.html) require that ownership of the connection, so we likely need to make specialized pool connection implementations to accommodate these features.

**Comment by genusistimelord** [comment]
If we re-add back the ability to Remove the connection from our wrapper and add it back in then this will be possible. Otherwise you have to manually implement all the pubsub stuff. since it doesn't seem they are traits. This should work since PubSub also supports [into_connection](https://docs.rs/redis/latest/redis/aio/struct.PubSub.html#method.into_connection)

Monitor does not support this though so in this case the Connection used is just lost from our pool. But that is OK since the pool can keep creating new connections.

the old method had a https://github.com/AscendingCreations/RedisPool/blob/a0e65ad51211f670d116aa420b811996eecd4bf0/src/pool/connection.rs#L22C5-L22C5

If we re-implement this method then we will be able to pull the connection out and then add another method to pull it back in.
you will however need to fix drop https://github.com/AscendingCreations/RedisPool/blob/main/src/connection.rs#L37
so it doesn't trigger a unwrap() and instead ignores it if it is none.

**Comment by wilgaboury** [comment]
I would favor both implementing a specialized pubsub/monitor wrapper, as to have first-class support for those features while also reintroducing a detach function in case any library users need that flexibility.

**Comment by genusistimelord** [comment]
that works for me. its basically copying their code and changing it to our connection type.

**Comment by genusistimelord** [comment]
#5 fixes this
