### ISSUE TITLE
Sample code does not work.

### ISSUE THREAD

**Issue by Magicloud** [AscendingCreations/RedisPool#9]
This code gives me following error.

```
    let client =
        redis::Client::open(args.redis_address).expect("Error while testing the connection");
    let pool = RedisPool::from(client);
```

```
the trait bound `RedisPool<_, _>: From<redis::Client>` is not satisfied
the trait `From<redis::client::Client>` is implemented for `RedisPool<redis::client::Client, redis::aio::connection::Connection>`
for that trait implementation, expected `redis::client::Client`, found `redis::Client`
```

**Comment by genusistimelord** [comment]
I  pushed a new version of Redis Pool to support Redis 0.25 as it was set to 0.24 and we had not yet updated since 0.25 breaks monitor and such. Anyways the new crate changes are a massive change as the databases are now split into their own crates. Please refer to the Examples and read me on how to set it up.

**Comment by Magicloud** [comment]
Thanks.
